### ISSUE TITLE
Tunes missing from tune_popularity.json

### ISSUE THREAD

**Issue by jamesamcl** [adactio/TheSession-data#14]
Hi, thanks for providing this dump. It seems that some tunes are missing from tune_popularity.json. For example, https://thesession.org/tunes/10082 shows that the tune has been added to 8 tunebooks. But,

    grep "10082" tune_popularity.json

yields no result?

**Comment by adactio** [comment]
Yes, there's a minimum number of 10 tunebooks that a tune needs to be added to in order to appear in the list. Partly this is to keep the list a bit more manageable in terms of file size, but also it's to keep the data somewhat statistically significant.

I could remove this limit if there were a use case for doing so. Can you describe what you're doing with the data?

**Comment by jamesamcl** [comment]
That's absolutely fine for my use case - I'm just making some graphs at this point and my script choked on the assumption that all tunes were also in the popularity file. It would be nice if this was documented however.
